### ISSUE TITLE
ImageName should be able to handle names with empty tag and digest(Valid form B -"hello-world:@%s")

### ISSUE THREAD

**Issue by Devashishbasu** [eclipse/jkube#2688] opened 2024-02-16 19:27 UTC
### Describe the bug

ImageName including ":" in image part

example :- 'registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9'
In this docker name the image part is 'hello-world' but it is extracting it as 'hello-world:'

ImageNameOSASReferenceTest output-

java.lang.IllegalArgumentException: Given Docker name 'registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9' is invalid:

image part 'hello-world:' doesn't match allowed pattern '[a-z0-9]+(?:(?:(?:[.]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[.]|__|[-]*)[a-z0-9]+)+)?)+)?'

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1.uncomment this test "registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9" in ImageNameOSASReferenceTest
2.Run this test
3.you will get error message like this
java.lang.IllegalArgumentException: Given Docker name 'registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9' is invalid:
image part 'hello-world:' doesn't match allowed pattern '[a-z0-9]+(?:(?:(?:[.]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[.]|__|[-]*)[a-z0-9]+)+)?)+)?'

### Expected behavior

ImageName should not include ":" in image part

### Runtime

minikube

### Kubernetes API Server version

1.25.3

### Environment

Windows

**Comment by Devashishbasu** [comment] 2024-02-16 19:29
Hi @rohanKanojia , @manusa...could you please review this issue ?
If it is correct than assign this to me

**Comment by rohanKanojia** [comment] 2024-02-20 05:46
@Devashishbasu : How is this issue different from https://github.com/eclipse/jkube/issues/2545?

**Comment by Devashishbasu** [comment] 2024-02-20 06:42
> @Devashishbasu : How is this issue different from #2545?

Hi @rohanKanojia   in #2545 you have mentioned "When both tag and digest are provided, the tag should be ignored and digest should be used" while working for the same i have noticed that ImageName is not extracting the imagepart correctly it is including ":" specifically for docker names with  empty tag and digest(Valid form B -"hello-world:@%s")...so for correct extraction of image part in docker name i have opened this issue....please correct me if i am wrong or misunderstood

**Comment by Devashishbasu** [comment] 2024-02-20 06:46
> @Devashishbasu : How is this issue different from #2545?

I think you are right ....the same solution will work for #2545

**Comment by Devashishbasu** [comment] 2024-02-20 06:48
> @Devashishbasu : How is this issue different from #2545?

So should i raise the same pr for #2545  which i have opened for this issue ?

**Comment by rohanKanojia** [comment] 2024-02-20 08:56
Duplicate of #2545

**Comment by rohanKanojia** [comment] 2024-02-20 08:56
Let's close this one as duplicate, you can create PR for #2545

**Closed by rohanKanojia** 2024-02-20 08:56 UTC
Labels: bug
