### ISSUE TITLE
Spring 3.2.1 [Error: Could not find or load main class org.springframework.boot.loader.JarLauncher]

### ISSUE THREAD

**Issue by AhmdFahad** [eclipse/jkube#2521] opened 2024-01-10 10:57 UTC
### JKube not working with Spring Boot 3.2.1

JKube can`t build docker image

```
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher

```

> Spring has change the path of JarLauncher

#FROM
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]

#TO
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]

### Eclipse JKube version

1.15.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

K8S:build

### Expected behavior

build an image 

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Windows

**Comment by rohanKanojia** [comment] 2024-01-10 11:00
Duplicate of #2477

**Comment by manusa** [comment] 2024-01-10 11:00
Duplicate of #2477 will be fixed in next minor release 1.16.0

**Comment by manusa** [comment] 2024-01-10 11:01
check workaround in the meantime https://github.com/eclipse/jkube/issues/2477#issuecomment-1828004196

**Comment by rohanKanojia** [comment] 2024-01-10 11:02
@AhmdFahad : Could you please check if you can resolve issue by using `1.16-SNAPSHOT`? You can check how to use JKube Snapshot artifacts [here](https://github.com/eclipse/jkube/blob/master/USING-SNAPSHOT-ARTIFACTS.md).

**Comment by AhmdFahad** [comment] 2024-01-10 11:12
@rohanKanojia  

it`s working 🎇🎆

![image](https://github.com/eclipse/jkube/assets/68047377/661dc98d-ec65-4754-a6ac-e6b4757ae39b)

**Closed** 2024-01-10 11:24 UTC
Labels: bug
