### ISSUE TITLE
Apply configuration in DependencyEnricher

### ISSUE THREAD

**Issue by rnetuka** [eclipse/jkube#658] opened 2021-04-09 07:20 UTC
In DependencyEnricher, configuration is not taken into account. For example if you have two projects, one depends
on another, and you run

```
 > cd project_A
 > mvn oc:resource -Djkube.replicas=2
```

it creates
_target/classes/META-INF/jkube/openshift/project_A_deploymentconfig.yml_
with `spec.replicas: 2`
_target/classes/META-INF/jkube/openshift/project_B_deploymentconfig.yml_
with `spec.replicas: 1`

It would be nice to overwrite the replica count in DependencyEnricher just as DefaultControllerEnricher does. Also, apply other configuration that makes sense.

**Comment by manusa** [comment] 2021-04-09 07:37
Hi @rnetuka ,
Thx for reporting the issue.
As discussed, let us further investigate the issue. DependencyEnricher hasn't been revisited in a long time and it's possible that we're missing other configurations too (besides replicas).

**Comment by rnetuka** [comment] 2021-04-13 14:15
PR https://github.com/eclipse/jkube/pull/660

**Comment by manusa** [comment] 2021-04-14 10:52
I think the solution for this issue might be as simple as switching the order of the Enrichers
These lines:
https://github.com/eclipse/jkube/blob/4809716a08ab90ddf9ec7e7d329e5b7e020630a9/openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml#L32
https://github.com/eclipse/jkube/blob/4809716a08ab90ddf9ec7e7d329e5b7e020630a9/kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml#L32

Should be moved to the top.

Have you tried that?

**Comment by manusa** [comment] 2021-04-14 11:52
> Have you tried that?

I've tried this with a few more changes like changing the override from `enrich` to `create`, but the problem is really not with the `DependencyEnricher` implementation (maybe the order should be fixed either way). 

The problem is about what we expect from this Enricher and the behavior of the `-Djkube.replicas` modifier.

The enricher basically merges **materialized** YAML configurations that come from dependencies. The fact that they are materialized, means that these YAMLs are to be considered as fragments of the dependent project.

So following with the -Djkube.replicas modifier, the behavior of this flag is to set the number of replicas for **generated** manifests. This means that for the case where a manifest is completely generated from JKube (**and** didn't contain a `spec.replicas` field), the value of the replicas will be set for us.
If this is combined with a fragment that contains a `spec.replicas` field with a value, the value coming from that field will prevail (same as with the DependencyEnricher).

So perhaps, what we want to change is the fact that if we provide a -Djkube.replicas modifier, this value should always take precedence on top of any other value provided elsewhere (dependent YAML, fragments, enricher configurations, etc.)

**Comment by manusa** [comment] 2021-04-14 12:02
A possible solution compliant with our current state might be to create a new Enricher whose sole responsibility would be to set/enforce the number of replicas for any Controller resource despite whatever comes from a Fragment, XML config, etc.

The value would only be set by providing the -Djkube.replicas property:
https://github.com/eclipse/jkube/blob/0a1b6b156d1b2b6ec3799430a6167e488986caea/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L203-L204

That would then be used to set a value `enforcedReplicas` in the ResourceConfig (instead of the current replicas):
https://github.com/eclipse/jkube/blob/0a1b6b156d1b2b6ec3799430a6167e488986caea/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L263

This enricher would be placed last in the order of execution.

Thoughts?

**Comment by rnetuka** [comment] 2021-04-15 08:36
Sounds good to me.

**Comment by rnetuka** [comment] 2021-04-20 14:14
@manusa I've created PR https://github.com/eclipse/jkube/pull/675. Could you please take a look at it when you have time?

**Closed** 2021-05-17 11:29 UTC
Labels: bug
