### ISSUE TITLE
Quickstarts: Port Quarkus quickstart

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1243] opened 2022-01-27 14:12 UTC
## Description

Child of #31 

Port quarkus Maven quickstart to Gradle.

**Comment by anurag-rajawat** [comment] 2022-05-16 16:57
@manusa this issue is fixed by #1443
So, we can close this one.

**Comment by rohanKanojia** [comment] 2022-05-16 17:09
Duplicate of https://github.com/eclipse/jkube/issues/1431

**Closed by rohanKanojia** 2022-05-16 17:09 UTC
Labels: component/gradle-plugin
