### ISSUE TITLE
Fix `jkube-kit/build/service` module's unit tests on Windows 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2640] opened 2024-02-08 07:26 UTC
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

_Originally posted by @l3002 in https://github.com/eclipse/jkube/issues/2629#issuecomment-1933484184_

> a few tests are still failing in `jkube-kit/build/service` module. Here's a screenshot for your reference

When running `mvn clean install` on Windows, I see the following tests failing in `jkube-kit/build/service` module:

- [WatchServiceTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java)

TODO: Figure out what's not working as expected and propose a way to fix this

![Screenshot 2024-02-08 124307](https://github.com/eclipse/jkube/assets/111552820/d77ec2b3-06a3-4e57-a248-c3580b7e9409)

**Comment by l3002** [comment] 2024-02-08 08:19
@rohanKanojia, I can pick this up, Please assign this to me.

**Comment by rohanKanojia** [comment] 2024-02-08 08:22
I haven't checked what's causing the failure. Make sure you share your findings for root cause first before fixing the issue.

**Comment by l3002** [comment] 2024-02-13 17:29
@rohanKanojia, I have been a bit busy over the past few days, I hope it won't be a problem if this takes a few more day?

**Comment by rohanKanojia** [comment] 2024-02-13 17:46
@l3002  : No problem, take your time.

**Comment by l3002** [comment] 2024-02-14 20:00
@rohanKanojia, Seems like the problem is occurring due to the outputDirectory used in WatchContext.buildContext. See below:

![image](https://github.com/eclipse/jkube/assets/111552820/d0c4b2c1-b89b-4d78-8b90-fb1311e9d6e8)

Here, we are using the absolute path of the directory rather than using just the name. Due to which when we invoke BuildDirs.getDir(), it uses that absolute path of the output directory rather than just using the name of the output directory.

![image](https://github.com/eclipse/jkube/assets/111552820/26c3e3c4-fdea-4b3e-b62a-e28e55e2fd0e)

This method then returns a file path like this:

`C:\Users\Tdgf\AppData\Local\Temp\junit8869024635707207334\C:\Users\Tdgf\AppData\Local\Temp\junit8869024635707207334\target\test-app\build`

and is used in the BuildDirs.createDir() leading to the throw statement

![image](https://github.com/eclipse/jkube/assets/111552820/bfbcc97f-de37-4a39-8b8b-497641e82e89)

We can solve the issue by changing the absolute path to just the name. See below:

![image](https://github.com/eclipse/jkube/assets/111552820/cff36671-d7f3-434a-8cae-e5e5276dc520)

Changing the getAbsolutePath() to getName().

**Comment by rohanKanojia** [comment] 2024-02-15 18:04
@l3002 : Nice work! Your analysis looks correct to me. `outputDirectory` is a relative path to base directory not absolute path.

It was working incorrectly on Linux as well, but we didn't notice it because on Linux it was creating nested directories:
```
/tmp/junit15664568372380832823
├── file.txt
├── target
└── tmp
    └── junit15664568372380832823
        └── target
            └── test-app
                ├── build
                └── work
```

**Comment by l3002** [comment] 2024-02-15 18:49
@rohanKanojia: Thanks, Should I raise a PR with the mentioned changes? 

Also, After making those changes to the fork on my local system and building the project, there is still a unit test failing in enricher module. Could you please create an issue for that too? 

![image](https://github.com/eclipse/jkube/assets/111552820/3a625d28-5173-438f-a9cd-4ca43f1475e4)

While building the project in windows, the following test seems to be failing in `jkube-kit/enricher/api` module:
- MetadataVisitorTest

**Comment by rohanKanojia** [comment] 2024-02-15 18:51
You can go ahead and create pull request 👍

**Comment by rohanKanojia** [comment] 2024-02-15 18:53
> Also, After making those changes to the fork on my local system and building the project, there is still a unit test failing in enricher module. Could you please create an issue for that too? 
> 
> ![image](https://github.com/eclipse/jkube/assets/111552820/3a625d28-5173-438f-a9cd-4ca43f1475e4)
> 
> While building the project in windows, the following test seems to be failing in `jkube-kit/enricher/api` module:
> - MetadataVisitorTest
> 


Please don't hesitate in opening up new issue on repository. Anyone can create issues. Just try to follow the same format I used in previous issues.

**Comment by l3002** [comment] 2024-02-15 18:56
Got it.

**Comment by manusa** [comment] 2024-02-16 05:54
> This method then returns a file path like this:
> 
> `C:\Users\Tdgf\AppData\Local\Temp\junit8869024635707207334\C:\Users\Tdgf\AppData\Local\Temp\junit8869024635707207334\target\test-app\build`


> It was working incorrectly on Linux as well, but we didn't notice it because on Linux it was creating nested directories:


I haven't checked, but this looks like a bug. Probably we should warn about this or even throw an exception if this configuration is provided.

**Comment by rohanKanojia** [comment] 2024-02-16 06:14
This `outputDirectory` field is set from plugins

https://github.com/eclipse/jkube/blob/5e5b596a026c772cfee561b8a74880bf816b3f44/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L437

https://github.com/eclipse/jkube/blob/5e5b596a026c772cfee561b8a74880bf816b3f44/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java#L140

It's default value is set to `outputDir/docker` if not set:

https://github.com/eclipse/jkube/blob/5e5b596a026c772cfee561b8a74880bf816b3f44/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L171-L172

https://github.com/eclipse/jkube/blob/5e5b596a026c772cfee561b8a74880bf816b3f44/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java#L608

**Comment by manusa** [comment] 2024-02-16 06:19
Yes, I know.
This is exactly my point. Maybe we want to warn those users who provide an absolute path in the `outputDirectory` configuration, since JKube won't behave as they expect to.

**Comment by l3002** [comment] 2024-02-16 10:39
@manusa, I had a concern regarding this too, if this was undetected here then anyone configuring it manually might face issue later on. We should provide exception if anyone tries to use the absolute path instead to the relative path.

**Closed** 2024-02-19 16:17 UTC
Labels: help wanted
