### ISSUE TITLE
Avoid initContainer while mounting a volume

### ISSUE THREAD

**Issue by thibaut-fluteaux-infy** [eclipse/jkube#1179] opened 2021-12-20 16:29 UTC
### Description
Since I switch from fabric8 to JKUBE, When I add a volume in my description.yaml.
An initContainer using busybox is automatically added, was not the case with fabric8.

The main issue, my openshift instance dont have access to busybox image (due to corporate restriction)
### Info

* Eclipse JKube version : 1.4.0
* Maven version (`mvn -v`) : 3.8.1
```

```
* Kubernetes / Red Hat OpenShift setup and version : 3.11

**Comment by rohanKanojia** [comment] 2021-12-20 16:59
Is this duplicate of https://github.com/eclipse/jkube/issues/891 ? If yes, you might be able to specify image like this:
```yaml
<plugin>
    <groupId>org.eclipse.jkube</groupId>
    <artifactId>kubernetes-maven-plugin</artifactId>
    <version>${jkube.version}</version>
    <configuration>
      <enricher>
        <config>
            <jkube-volume-permission>
              <imageName>name-foo</imageName>
            </jkube-volume-permission>
        </config>
      </enricher>
    </configuration>
</plugin>
```

**Comment by te3ex** [comment] 2021-12-21 07:55
Thanks for the help to change the image, is their any option to avoid the usage of init container ? 
with Fabric8 it was fully working without initcontainer.

regards,

**Comment by thibaut-fluteaux-infy** [comment] 2021-12-21 07:59
Thanks for the help to change the image, is there any option to avoid the usage of init container ?
with Fabric8 it was fully working without initcontainer.
regards,

**Comment by rohanKanojia** [comment] 2021-12-21 08:20
@thibaut-fluteaux-infy : Would it be possible for you to share a reproducer project? I will help me debug cause for behavioral difference between two plugins.

**Comment by thibaut-fluteaux-infy** [comment] 2021-12-21 09:46
considering volumeclaim "volumetest" allready exist.
here is my reproducer : https://github.com/thibaut-fluteaux-infy/jkube-kmp
maven profile : 
    -fmp for fabric8
    -jkube for jkube
    
 regards

**Comment by rohanKanojia** [comment] 2021-12-21 13:19
I see you're using quite an old version of the Fabric8 Maven Plugin. I tried with the latest version of FMP v4.4.1 and I was able to see initContainers generated.

I think this change was done by me in https://github.com/fabric8io/fabric8-maven-plugin/pull/1318

**Comment by thibaut-fluteaux-infy** [comment] 2021-12-21 13:27
thanks for your answer,  no way to disable the usage of init container by jkube ?

**Comment by rohanKanojia** [comment] 2021-12-21 13:33
Right now, no. If you want we can add a configuration option to disable this here:

https://github.com/eclipse/jkube/blob/cce1b0de09a3657ec9000b3097d7266daa49aaec/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L94

However, we need to decide if it's really the way we would like to go.

**Comment by thibaut-fluteaux-infy** [comment] 2021-12-21 15:17
> 

After defining this,   busybox is still used ...  
am i miss something ?

**Comment by kuailexingmao** [comment] 2022-01-07 01:53
I encountered the same problem and did not want to use initContainer automatically loaded in Depl0ymentConfig, so I disabled jkube-volume-Permission.My configuration is as follows:
`<configuration>`
      `    <enricher>`
        `     <excludes>`
                 jkube-volume-permission
        `     <excludes>`
      `    </enricher>`
    `</configuration>`

**Comment by rohanKanojia** [comment] 2023-01-03 17:15
I've moved out functionality unrelated to Volume permissions in #1179 

Now in order to avoid initContainer you just need to exclude the enricher as @kuailexingmao suggested.

**Closed** 2023-03-27 12:03 UTC
Labels: enhancement
