### ISSUE TITLE
Publish Helm charts on repository

### ISSUE THREAD

**Issue by dloiacono** [eclipse/jkube#580] opened 2021-02-17 17:33 UTC
### Description
Is not possible to publish the created helm chart in some helm repository

### Info

* Eclipse JKube version : 1.1.0
* Maven version (`mvn -v`) :
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case : I want to publish the Helm chart to use it in the prod environment

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment] 2021-02-17 17:57
Duplicate of https://github.com/eclipse/jkube/issues/576

**Comment by manusa** [comment] 2021-03-25 09:22
Closing this in favor of #576

**Closed by manusa** 2021-03-25 09:22 UTC
